### ISSUE TITLE
Erro ao instalar - invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by aceccarelli** [thalestpires/redmine_bpm_integration#2]
Olá Thales, tudo bem?

Quando rodo o comando para instalar o plugin está apresentando este erro abaixo:

<pre>
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/trace_output.rb:16:in `block in trace_on': invalid byte sequence in US-ASCII (ArgumentError)
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/trace_output.rb:14:in `map'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/trace_output.rb:14:in `trace_on'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:376:in `trace'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:222:in `display_exception_message_details'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:209:in `display_exception_details'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:198:in `display_error_message'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:185:in `rescue in standard_exception_handling'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
        from /usr/local/bin/rake:23:in `load'
        from /usr/local/bin/rake:23:in `<main>'
</pre>

Configurações do meu ambiente:

<pre>
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
</pre>

**Comment by victorlcampos** [comment]
@aceccarelli, acredito que o plugin só funcione na versão 3.1 do Redmine

**Comment by aceccarelli** [comment]
Opa!
Conforme orientação, instalei a versão 3.1.1 e o problema persiste. Se puder me ajudar, agradeço muito, pois estou curioso e querendo utilizar seu plugin.

<pre>
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/trace_output.rb:16:in `block in trace_on': invalid byte sequence in US-ASCII (ArgumentError)
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/trace_output.rb:14:in `map'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/trace_output.rb:14:in `trace_on'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:376:in `trace'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:222:in `display_exception_message_details'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:209:in `display_exception_details'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:198:in `display_error_message'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:185:in `rescue in standard_exception_handling'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
        from /usr/local/bin/rake:23:in `load'
        from /usr/local/bin/rake:23:in `<main>'
</pre>

<pre>
Environment:
  Redmine version                3.1.1.devel
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
</pre>

**Comment by lucasarnaud** [comment]
@aceccarelli, a versão do ruby que estamos usando para o desenvolvimento é a 2.2.2. Que comando você está rodando? "rails generate delayed_job:active_record rake db:migrate"?

**Comment by aceccarelli** [comment]
@lucasarnaud 
Não, o primeiro comando para instalar o plugin. Nem passou desta etapa.

rake redmine:plugins:migrate RAILS_ENV=production

Valeu!

**Comment by aceccarelli** [comment]
Olá @lucasarnaud !

Instalei a nova versão do Redmine e o erro ainda persiste.

<pre>
Environment:
  Redmine version                3.2.0.devel
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
</pre>

Erro:

<pre>
linux:/sistema/redmine320/plugins# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /sistema/redmine320)
rake aborted!
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/trace_output.rb:16:in `block in trace_on': invalid byte sequence in US-ASCII (ArgumentError)
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/trace_output.rb:14:in `map'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/trace_output.rb:14:in `trace_on'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:376:in `trace'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:222:in `display_exception_message_details'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:209:in `display_exception_details'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:198:in `display_error_message'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:185:in `rescue in standard_exception_handling'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
        from /var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
        from /usr/local/bin/rake:23:in `load'
        from /usr/local/bin/rake:23:in `<main>'
linux:/sistema/redmine320/plugins#
</pre>

**Comment by lucasarnaud** [comment]
@aceccarelli, tentei realizar o procedimento de instalação desde o início nas mesmas configurações de ambientes que você está utilizando. Após fazer o _checkout_ da versão mais recente do _trunk_ do repositório oficial do Redmine, o comando, para configuração inicial do banco,

```rake db:migrate```

já apresenta o mesmo erro que você está tendo, sem a instalação de _plugin_ algum.

A configuração que utilizamos no nosso ambiente de produção é a seguinte:

    Environment:
      Redmine version                3.1.1.stable
      Ruby version                   2.1.6-p336 (2015-04-13) [x86_64-linux]
      Rails version                  4.2.4
      Environment                    production
      Database adapter               Mysql2

Tente atualizar a versão do **Ruby** que você está utilizando que deve solucionar o seu problema.
